# This is a Kubernetes Pod configuration file.

# The `apiVersion` specifies the version of the Kubernetes API used for this resource.
apiVersion: v1

# The `kind` specifies the type of resource. Here, it is a Pod.
kind: Pod

# The `metadata` section contains information about the Pod itself.
# `name` is the unique name assigned to this Pod within the namespace.
metadata:
  name: harry-webapp
# Labels are key-value pairs used to organize and select Kubernetes resources. 
# The keys and values can be anything you define (it can be like mylabelname: harry-webapp also), as long as they meet Kubernetes naming conventions
  labels:
    app: harry-webapp
    tier: frontend

# The `spec` section defines the desired state and behavior of the Pod.  
spec:
  containers:
  - name: dockerkubernetesminikube
    image: hareesh52/dockerkubernetesminikube:v3
    ports:
    - containerPort: 9002