apiVersion: v1
kind: Service
metadata:
  name: harry-webapp-nodeport-service

spec:
  selector:
    app: harry-webapp

  ports:
    - name: http
      port: 80
      targetPort: 9002
      nodePort: 30080

  type: NodePort
  externalTrafficPolicy: Local