apiVersion: v1
kind: Service
metadata:
  name: harry-webapp-loadbalancer-service
  namespace: default
spec:
  selector:
    app: harry-webapp
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    port: 80
    targetPort: 9002
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
